language: r
r: release
cache: packages
warnings_are_errors: false
r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

bioc_packages:
  - NMF
  - SummarizedExperiment
  - phylobase
  - dendextend
  - clusterExperiment
  - SingleCellExperiment
  - ggplot2
  - ggbeeswarm
  - shiny
  - shinydashboard
  - scater
sudo: required
r_binary_packages:
  - reshape
  - memoise
  - deoptimr
  - iterators
  - dichromat
  - munsell
  - labeling
  - dbi
  - rsqlite
  - foreach
  - rcppeigen
  - gtable
  - xtable
  - hdf5
  - rcolorbrewer
  - stringr
  - reshape2
r_packages:
  - rjson
  - robustbase
  - bitops
  - plyr
  - scales
  - RCurl
  - mvtnorm
  - colorspace
  - digest
  - XML
  - kernlab
  - matrixStats
  - ape
  - gridExtra
  - httpuv
  - covr
  - modeltools
  - doParallel
  - ade4
  - stringi
  - beeswarm
  - Rcpp
  - Rtsne
after_success:
  - Rscript -e 'covr::codecov()'
